import type { EmailDispatch } from "./types";

export const mockDispatches: EmailDispatch[] = [
  {
    id: "dispatch-001",
    campaignName: "Empresas PR por CNAE",
    recipientEmail: "contato@empresaexemplo.com.br",
    subject: "Campanha teste certificação digital",
    status: "sent",
    provider: "Mailpit",
    attemptCount: 1,
    maxAttempts: 3,
    queuedAt: "2026-05-02T13:40:00.000Z",
    sentAt: "2026-05-02T13:41:12.000Z",
    lastError: null,
  },
  {
    id: "dispatch-002",
    campaignName: "Oferta Grupo Expand",
    recipientEmail: "financeiro@cliente.com.br",
    subject: "Conheça nossa solução",
    status: "failed",
    provider: "Gmail SMTP",
    attemptCount: 3,
    maxAttempts: 3,
    queuedAt: "2026-05-02T13:38:00.000Z",
    failedAt: "2026-05-02T13:39:20.000Z",
    lastError: "SMTP authentication failed.",
  },
  {
    id: "dispatch-003",
    campaignName: "Newsletter Maio",
    recipientEmail: "lead@empresa.com.br",
    subject: "Atualizações importantes",
    status: "queued",
    provider: "Mailpit",
    attemptCount: 0,
    maxAttempts: 3,
    queuedAt: "2026-05-02T13:45:00.000Z",
    lastError: null,
  },
  {
    id: "dispatch-004",
    campaignName: "Reativação de Leads",
    recipientEmail: "compras@industria.com.br",
    subject: "Vamos retomar contato?",
    status: "retrying",
    provider: "Mailpit",
    attemptCount: 2,
    maxAttempts: 3,
    queuedAt: "2026-05-02T13:20:00.000Z",
    lastError: "Temporary provider timeout.",
  },
];
