import type { MonitoredCampaign } from "./types";

export const mockMonitoredCampaigns: MonitoredCampaign[] = [
  {
    id: "campaign-monitor-001",
    campaignName: "Empresas PR por CNAE",
    subject: "Campanha teste certificação digital",
    status: "processing",
    provider: "Mailpit",
    smtpSenderName: "Mailpit — Mail Engine",
    smtpFromEmail: "no-reply@example.com",
    startedAt: "2026-05-02T13:40:00.000Z",
    finishedAt: null,
    totalRecipients: 8,
    sentCount: 5,
    failedCount: 2,
    queuedCount: 1,
    retryingCount: 0,
    maxAttempts: 3,
    deliveries: [
      {
        id: "delivery-001",
        recipientEmail: "contato@empresaexemplo.com.br",
        leadName: "Empresa Exemplo",
        companyName: "Empresa Exemplo LTDA",
        status: "sent",
        attemptCount: 1,
        maxAttempts: 3,
        queuedAt: "2026-05-02T13:40:00.000Z",
        sentAt: "2026-05-02T13:41:12.000Z",
        providerMessageId: "mailpit-msg-001",
        smtpResponse: "250 Message accepted",
      },
      {
        id: "delivery-002",
        recipientEmail: "financeiro@cliente.com.br",
        leadName: "Cliente Financeiro",
        companyName: "Cliente Comércio LTDA",
        status: "failed",
        attemptCount: 3,
        maxAttempts: 3,
        queuedAt: "2026-05-02T13:40:10.000Z",
        failedAt: "2026-05-02T13:44:20.000Z",
        lastError: "SMTP authentication failed.",
        smtpResponse: "535 Authentication failed",
      },
      {
        id: "delivery-003",
        recipientEmail: "compras@industria.com.br",
        leadName: "Indústria Compras",
        companyName: "Indústria Paraná SA",
        status: "failed",
        attemptCount: 3,
        maxAttempts: 3,
        queuedAt: "2026-05-02T13:40:18.000Z",
        failedAt: "2026-05-02T13:45:01.000Z",
        lastError: "Recipient domain rejected the message.",
        smtpResponse: "550 Mailbox unavailable",
      },
      {
        id: "delivery-004",
        recipientEmail: "lead@empresa.com.br",
        leadName: "Lead Empresa",
        companyName: "Empresa de Serviços ME",
        status: "queued",
        attemptCount: 0,
        maxAttempts: 3,
        queuedAt: "2026-05-02T13:45:00.000Z",
      },
    ],
    timeline: [
      {
        id: "event-001",
        title: "Campanha preparada",
        description:
          "Os destinatários foram carregados e o conteúdo foi renderizado.",
        occurredAt: "2026-05-02T13:39:30.000Z",
        status: "info",
      },
      {
        id: "event-002",
        title: "Fila iniciada",
        description: "Os e-mails começaram a ser enviados pelo worker.",
        occurredAt: "2026-05-02T13:40:00.000Z",
        status: "success",
      },
      {
        id: "event-003",
        title: "Falhas detectadas",
        description:
          "Alguns destinatários retornaram erro SMTP após as tentativas.",
        occurredAt: "2026-05-02T13:45:01.000Z",
        status: "danger",
      },
    ],
  },
  {
    id: "campaign-monitor-002",
    campaignName: "Oferta Grupo Expand",
    subject: "Conheça nossa solução",
    status: "failed",
    provider: "Gmail SMTP",
    smtpSenderName: "[Daniel Arndt] [arndtimoveis]",
    smtpFromEmail: "daniel@arndtimoveis.com.br",
    startedAt: "2026-05-02T10:38:00.000Z",
    finishedAt: "2026-05-02T10:42:20.000Z",
    totalRecipients: 3,
    sentCount: 0,
    failedCount: 3,
    queuedCount: 0,
    retryingCount: 0,
    maxAttempts: 3,
    deliveries: [
      {
        id: "delivery-005",
        recipientEmail: "diretoria@grupoexpand.com.br",
        companyName: "Grupo Expand",
        status: "failed",
        attemptCount: 3,
        maxAttempts: 3,
        queuedAt: "2026-05-02T10:38:00.000Z",
        failedAt: "2026-05-02T10:42:20.000Z",
        lastError: "SMTP authentication failed.",
        smtpResponse: "535 Username and Password not accepted",
      },
      {
        id: "delivery-006",
        recipientEmail: "comercial@grupoexpand.com.br",
        companyName: "Grupo Expand",
        status: "failed",
        attemptCount: 3,
        maxAttempts: 3,
        queuedAt: "2026-05-02T10:38:06.000Z",
        failedAt: "2026-05-02T10:42:24.000Z",
        lastError: "SMTP authentication failed.",
        smtpResponse: "535 Username and Password not accepted",
      },
    ],
    timeline: [
      {
        id: "event-004",
        title: "Dispatch criado",
        description: "A campanha foi enviada para processamento.",
        occurredAt: "2026-05-02T10:37:50.000Z",
        status: "info",
      },
      {
        id: "event-005",
        title: "Erro de autenticação SMTP",
        description:
          "O provedor recusou a autenticação do remetente configurado.",
        occurredAt: "2026-05-02T10:42:20.000Z",
        status: "danger",
      },
    ],
  },
];
