/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verifica a saúde da API e suas dependências */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "ok" | "error";
              /** @enum {string} */
              service: "control-api";
              environment: string;
              /** Format: date-time */
              timestamp: string;
              checks: {
                postgres: {
                  /** @enum {string} */
                  status: "ok" | "error";
                  details?: string;
                };
                redis: {
                  /** @enum {string} */
                  status: "ok" | "error";
                  details?: string;
                };
              };
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "ok" | "error";
              /** @enum {string} */
              service: "control-api";
              environment: string;
              /** Format: date-time */
              timestamp: string;
              checks: {
                postgres: {
                  /** @enum {string} */
                  status: "ok" | "error";
                  details?: string;
                };
                redis: {
                  /** @enum {string} */
                  status: "ok" | "error";
                  details?: string;
                };
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista campaigns com paginação */
    get: {
      parameters: {
        query?: {
          status?:
            | "draft"
            | "ready"
            | "scheduled"
            | "running"
            | "paused"
            | "completed"
            | "canceled"
            | "failed";
          audienceId?: string;
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                id: string;
                name: string;
                goal: null | string;
                subject: null | string;
                /** @enum {string} */
                status:
                  | "draft"
                  | "ready"
                  | "scheduled"
                  | "running"
                  | "paused"
                  | "completed"
                  | "canceled"
                  | "failed";
                templateId: null | string;
                audienceId: null | string;
                audience: {
                  /** @example audience-001 */
                  id: string;
                  /** @example Empresas PR por CNAE */
                  name: string;
                  description: string | null;
                  /** @enum {string} */
                  sourceType: "cnpj-api" | "csv-import" | "manual-list";
                  filters: {
                    [key: string]: unknown;
                  };
                } | null;
                /** Format: date-time */
                scheduleAt: null | string;
                /** Format: date-time */
                lastExecutionAt: null | string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              }[];
              page: number;
              pageSize: number;
              total: number;
              totalPages: number;
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Cria uma campaign
     * @description Cria uma campaign e vincula templateId e audienceId quando informados.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example Campanha B2B Sul */
            name: string;
            goal?: string | null;
            subject?: string | null;
            /**
             * @default draft
             * @enum {string}
             */
            status?:
              | "draft"
              | "ready"
              | "scheduled"
              | "running"
              | "paused"
              | "completed"
              | "canceled"
              | "failed";
            templateId?: string | null;
            /** @example audience-001 */
            audienceId?: string | null;
            /** Format: date-time */
            scheduleAt?: string | null;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              goal: null | string;
              subject: null | string;
              /** @enum {string} */
              status:
                | "draft"
                | "ready"
                | "scheduled"
                | "running"
                | "paused"
                | "completed"
                | "canceled"
                | "failed";
              templateId: null | string;
              audienceId: null | string;
              audience: {
                /** @example audience-001 */
                id: string;
                /** @example Empresas PR por CNAE */
                name: string;
                description: string | null;
                /** @enum {string} */
                sourceType: "cnpj-api" | "csv-import" | "manual-list";
                filters: {
                  [key: string]: unknown;
                };
              } | null;
              /** Format: date-time */
              scheduleAt: null | string;
              /** Format: date-time */
              lastExecutionAt: null | string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulta uma campaign por id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              goal: null | string;
              subject: null | string;
              /** @enum {string} */
              status:
                | "draft"
                | "ready"
                | "scheduled"
                | "running"
                | "paused"
                | "completed"
                | "canceled"
                | "failed";
              templateId: null | string;
              audienceId: null | string;
              audience: {
                /** @example audience-001 */
                id: string;
                /** @example Empresas PR por CNAE */
                name: string;
                description: string | null;
                /** @enum {string} */
                sourceType: "cnpj-api" | "csv-import" | "manual-list";
                filters: {
                  [key: string]: unknown;
                };
              } | null;
              /** Format: date-time */
              scheduleAt: null | string;
              /** Format: date-time */
              lastExecutionAt: null | string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Atualiza parcialmente uma campaign */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            goal?: string | null;
            subject?: string | null;
            /** @enum {string} */
            status?:
              | "draft"
              | "ready"
              | "scheduled"
              | "running"
              | "paused"
              | "completed"
              | "canceled"
              | "failed";
            templateId?: string | null;
            audienceId?: string | null;
            /** Format: date-time */
            scheduleAt?: string | null;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              goal: null | string;
              subject: null | string;
              /** @enum {string} */
              status:
                | "draft"
                | "ready"
                | "scheduled"
                | "running"
                | "paused"
                | "completed"
                | "canceled"
                | "failed";
              templateId: null | string;
              audienceId: null | string;
              audience: {
                /** @example audience-001 */
                id: string;
                /** @example Empresas PR por CNAE */
                name: string;
                description: string | null;
                /** @enum {string} */
                sourceType: "cnpj-api" | "csv-import" | "manual-list";
                filters: {
                  [key: string]: unknown;
                };
              } | null;
              /** Format: date-time */
              scheduleAt: null | string;
              /** Format: date-time */
              lastExecutionAt: null | string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/campaigns/{id}/audience-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Gera preview da audience vinculada à campaign */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example audience-001 */
              audienceId?: string | null;
              /** @example campaign-001 */
              campaignId?: string | null;
              /**
               * @example cnpj-api
               * @enum {string}
               */
              sourceType: "cnpj-api" | "csv-import" | "manual-list";
              /** @example 20 */
              requestedLimit: number;
              /** @example 2 */
              count: number;
              items: {
                /**
                 * Format: email
                 * @example contato@empresa.com
                 */
                email: string;
                /** @example 12345678000199 */
                externalId: string | null;
                /**
                 * @example cnpj-api
                 * @enum {string}
                 */
                sourceType: "cnpj-api" | "csv-import" | "manual-list";
                /**
                 * @example {
                 *       "companyName": "Empresa A",
                 *       "city": "Londrina"
                 *     }
                 */
                metadata: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Default Response */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/email-dispatch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cria e enfileira um email dispatch */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/audiences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista audiences cadastradas */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                /** @example audience-001 */
                id: string;
                /** @example Empresas PR por CNAE */
                name: string;
                /** @example Audience voltada à prospecção de empresas do Paraná. */
                description?: string | null;
                definition: {
                  /**
                   * @example cnpj-api
                   * @enum {string}
                   */
                  sourceType: "cnpj-api" | "csv-import" | "manual-list";
                  /**
                   * @example {
                   *       "searchType": "cnae",
                   *       "codigosCnae": [
                   *         "6201501",
                   *         "6202300"
                   *       ],
                   *       "uf": "PR",
                   *       "municipio": "Londrina",
                   *       "page": 1,
                   *       "limit": 20
                   *     }
                   */
                  filters: {
                    [key: string]: unknown;
                  };
                };
                /** @example 2026-04-23T10:00:00.000Z */
                createdAt: string;
                /** @example 2026-04-23T10:00:00.000Z */
                updatedAt: string;
              }[];
              /** @example 1 */
              page: number;
              /** @example 20 */
              pageSize: number;
              /** @example 1 */
              total: number;
              /** @example 1 */
              totalPages: number;
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Cria uma audience persistida e reutilizável
     * @description Registra uma audience separadamente da campaign. Depois, a campaign pode apenas vincular o audienceId.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example Empresas PR por CNAE */
            name: string;
            /** @example Audience cadastrada a partir da CNPJ API. */
            description?: string | null;
            /**
             * @example cnpj-api
             * @enum {string}
             */
            sourceType: "cnpj-api" | "csv-import" | "manual-list";
            /**
             * @example {
             *       "searchType": "cnae",
             *       "codigosCnae": [
             *         "6201501",
             *         "6202300"
             *       ],
             *       "uf": "PR",
             *       "municipio": "Londrina",
             *       "page": 1,
             *       "limit": 20
             *     }
             */
            filters: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example audience-001 */
              id: string;
              /** @example Empresas PR por CNAE */
              name: string;
              /** @example Audience voltada à prospecção de empresas do Paraná. */
              description?: string | null;
              definition: {
                /**
                 * @example cnpj-api
                 * @enum {string}
                 */
                sourceType: "cnpj-api" | "csv-import" | "manual-list";
                /**
                 * @example {
                 *       "searchType": "cnae",
                 *       "codigosCnae": [
                 *         "6201501",
                 *         "6202300"
                 *       ],
                 *       "uf": "PR",
                 *       "municipio": "Londrina",
                 *       "page": 1,
                 *       "limit": 20
                 *     }
                 */
                filters: {
                  [key: string]: unknown;
                };
              };
              /** @example 2026-04-23T10:00:00.000Z */
              createdAt: string;
              /** @example 2026-04-23T10:00:00.000Z */
              updatedAt: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/audiences/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulta uma audience por id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example audience-001 */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example audience-001 */
              id: string;
              /** @example Empresas PR por CNAE */
              name: string;
              /** @example Audience voltada à prospecção de empresas do Paraná. */
              description?: string | null;
              definition: {
                /**
                 * @example cnpj-api
                 * @enum {string}
                 */
                sourceType: "cnpj-api" | "csv-import" | "manual-list";
                /**
                 * @example {
                 *       "searchType": "cnae",
                 *       "codigosCnae": [
                 *         "6201501",
                 *         "6202300"
                 *       ],
                 *       "uf": "PR",
                 *       "municipio": "Londrina",
                 *       "page": 1,
                 *       "limit": 20
                 *     }
                 */
                filters: {
                  [key: string]: unknown;
                };
              };
              /** @example 2026-04-23T10:00:00.000Z */
              createdAt: string;
              /** @example 2026-04-23T10:00:00.000Z */
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Exclui uma audience sem vínculos com campaigns */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example audience-001 */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example deleted */
              status: string;
              /** @example audience-001 */
              id: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              /** @example 1 */
              campaignsCount: number;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Atualiza parcialmente uma audience */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example audience-001 */
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example Novo nome da audience */
            name?: string;
            /** @example Descrição atualizada. */
            description?: string | null;
            /**
             * @example manual-list
             * @enum {string}
             */
            sourceType?: "cnpj-api" | "csv-import" | "manual-list";
            /**
             * @example {
             *       "recipients": [
             *         {
             *           "email": "novo@empresa.com"
             *         }
             *       ],
             *       "limit": 20
             *     }
             */
            filters?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example audience-001 */
              id: string;
              /** @example Empresas PR por CNAE */
              name: string;
              /** @example Audience voltada à prospecção de empresas do Paraná. */
              description?: string | null;
              definition: {
                /**
                 * @example cnpj-api
                 * @enum {string}
                 */
                sourceType: "cnpj-api" | "csv-import" | "manual-list";
                /**
                 * @example {
                 *       "searchType": "cnae",
                 *       "codigosCnae": [
                 *         "6201501",
                 *         "6202300"
                 *       ],
                 *       "uf": "PR",
                 *       "municipio": "Londrina",
                 *       "page": 1,
                 *       "limit": 20
                 *     }
                 */
                filters: {
                  [key: string]: unknown;
                };
              };
              /** @example 2026-04-23T10:00:00.000Z */
              createdAt: string;
              /** @example 2026-04-23T10:00:00.000Z */
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/audiences/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resolve destinatários por sourceType e filtros
     * @description Usa o provider configurado para o sourceType e retorna um preview direto dos destinatários. Para cnpj-api, consultar os exemplos em filters.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * @example cnpj-api
             * @enum {string}
             */
            sourceType: "cnpj-api" | "csv-import" | "manual-list";
            /**
             * @description Filtros dependem do sourceType. Para cnpj-api, usar searchType ou mode com cnae|razao-social|socio. Para audiences persistidas e previews, page e limit devem ficar dentro de filters.
             * @example {
             *       "searchType": "cnae",
             *       "codigosCnae": [
             *         "6201501"
             *       ],
             *       "uf": "PR",
             *       "municipio": "Londrina",
             *       "page": 1,
             *       "limit": 20
             *     }
             */
            filters: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example audience-001 */
              audienceId?: string | null;
              /** @example campaign-001 */
              campaignId?: string | null;
              /**
               * @example cnpj-api
               * @enum {string}
               */
              sourceType: "cnpj-api" | "csv-import" | "manual-list";
              /** @example 20 */
              requestedLimit: number;
              /** @example 2 */
              count: number;
              items: {
                /**
                 * Format: email
                 * @example contato@empresa.com
                 */
                email: string;
                /** @example 12345678000199 */
                externalId: string | null;
                /**
                 * @example cnpj-api
                 * @enum {string}
                 */
                sourceType: "cnpj-api" | "csv-import" | "manual-list";
                /**
                 * @example {
                 *       "companyName": "Empresa A",
                 *       "city": "Londrina"
                 *     }
                 */
                metadata: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Default Response */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/audiences/{id}/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Gera preview de uma audience persistida */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example audience-001 */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example audience-001 */
              audienceId?: string | null;
              /** @example campaign-001 */
              campaignId?: string | null;
              /**
               * @example cnpj-api
               * @enum {string}
               */
              sourceType: "cnpj-api" | "csv-import" | "manual-list";
              /** @example 20 */
              requestedLimit: number;
              /** @example 2 */
              count: number;
              items: {
                /**
                 * Format: email
                 * @example contato@empresa.com
                 */
                email: string;
                /** @example 12345678000199 */
                externalId: string | null;
                /**
                 * @example cnpj-api
                 * @enum {string}
                 */
                sourceType: "cnpj-api" | "csv-import" | "manual-list";
                /**
                 * @example {
                 *       "companyName": "Empresa A",
                 *       "city": "Londrina"
                 *     }
                 */
                metadata: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Default Response */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/email-dispatches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista email dispatches com filtros e paginação */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/email-dispatches/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulta um email dispatch por id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/email-dispatches/{id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reenfileira um email dispatch com status de erro */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista templates com paginação */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Cria um template */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/templates/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulta um template por id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    /** Exclui um template quando não houver dispatches vinculados */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** Atualiza parcialmente um template */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
